### ISSUE TITLE
encoding for stastbomb add_players_and_teams and add_events

### ISSUE THREAD

**Issue by chrisgschon** [ML-KULeuven/socceraction#11]
Thanks for the great work on making statsbomb data more accessible.

For the statsbomb.py functions, utf-8 encoding is declared for matches and competitions but not teams and players or events.

```
 with open(competition_file, "rt", encoding="utf-8") as fh:
            matches += json.load(fh)
```

vs.

```
with open(lineup_file, "r") as fh:
            lineups += json.load(fh)
```

This is causing my code to break as default decoding is ascii. Could the functions be aligned to utf-8? Alternatively - add try/except logic?

Thanks

Chris

**Comment by TomDecroos** [comment]
Fixed thanks to Donald's commit.
