### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by jmaccarty** [ML-KULeuven/socceraction#13]
Hi! first thanks for this package--I can't wait to dive into the "cleaned" data.
Second, I keep running into this error, and I think it has something to do with encodings in a few of the lineups, because if I remove certain line up files, it will run through. Sorry, I'm 99% an R user, so I'm not sure how to diagnose this! I'm following along in the open notebook you provided.

Thanks!

...Adding competitions to [redacted]\statsbomb.h5
...Adding matches to [redacted]\statsbomb.h5
...Adding players and teams to [redacted]\statsbomb.h5:  30%|▎| 168/551 [00:00<00:02, 133.37it/s]
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-4-0b9bd700b599> in <module>
----> 1 spadl.statsbombjson_to_statsbombh5("[redacted],statsbomb_h5)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\socceraction\spadl\statsbomb.py in jsonfiles_to_h5(datafolder, h5file)
     18     print(f"...Adding matches to {h5file}")
     19     add_matches(os.path.join(datafolder, "matches/"), h5file)
---> 20     add_players_and_teams(os.path.join(datafolder, "lineups/"), h5file)
     21     add_events(os.path.join(datafolder, "events/"), h5file)
     22 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\socceraction\spadl\statsbomb.py in add_players_and_teams(lineups_url, h5file)
     43     ):
     44         with open(lineup_file, "r") as fh:
---> 45             lineups += json.load(fh)
     46             for lineup in lineups:
     47                 for p in [flatten_id(p) for p in lineup["lineup"]]:

~\AppData\Local\Continuum\anaconda3\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 562: character maps to <undefined>

**Comment by jmaccarty** [comment]
I confirmed all the json are in UTF-8, and have even tried editing the statsbomb python source file downloaded to be Latin-1 encodings on import just as "Hm, let me try something but it probably won't work" and that doesn't work either

**Comment by probberechts** [comment]
The [default encoding used by Python 3 to read files is platform-specific](https://docs.python.org/3.5/library/functions.html#open): Windows uses cp1252 (similar to `latin-1`), while Linux uses `utf-8`. Since there are some non-latin characters in the player names, you got the UnicodeDecodeError on your system. This was already fixed in 367d02118fe525d210fb0405f9d7b2285e14311a by forcing the `open` call to use the `utf-8` encoding. It should work if you fetch the latest version of the code.
