### ISSUE TITLE
Lack of compatibility with Wyscout's Soccer-logs open dataset

### ISSUE THREAD

**Issue by kkoripl** [ML-KULeuven/socceraction#14]
Hi!
Lately i'm working with Wyscout's soccer-logs open dataset of matches' ball events and tried to calculate VAEP scores for each of passes made during games, as this would be needed for my masters thesis. There occured a problem though.

It looks like jsons files stored there are in different format/structure as "normal" Wyscout's ones, cause there is a problem with i.e. matches info not occuring in events jsons. As I found out it would be pretty easy to change actual jsons_to_h5 wyscout function to the one, which would load data from open dataset (as I probably got it right now), but I can't test it, not knowning values which would be produced by original algorithm. Probably I'd do pull request for you to look at this issue.

As it's said that SPADL/VAEP is compatible with Wyscout's data and looking for a bunch of people, who would probably use it and want to know results of your work, that could be a good feature to be added on, to work with this kind of data.

Best wishes!

Ed: forgot the link to dataset: https://figshare.com/collections/Soccer_match_event_dataset/4415000/2

**Comment by TomDecroos** [comment]
Hi kkoripl,

Thanks for flagging this. The core problem seems indeed to be that the soccerlog event data made available by Papalardo et al. is in a different format (i.e., matches.json, teams.json, event.json, players.json, ...) than how Wyscout usually provides their data through one self-contained file per match (match-1.json, match-2.json, match-3.json, ...)

Seeing how the soccerlog data set is probably going to be pretty important for many future soccer analytics researchers, I will try to add a converter to `socceraction` as soon as possible.

**Comment by kkoripl** [comment]
I came up with something like this and it seems working for me. Of course, there should be possibility to get seperate paths for matches, events, (you name it) files as arguments of function, but as I use only particular set in particular place that's how I did it.

def jsonfiles_to_h5(country, h5_file):
  with pd.HDFStore(h5_file) as store:
    events = load_events_as_df(country)
    match_ids = events[MATCH_ID].unique()
    for match_id in match_ids:
      store[f"events/match_{match_id}"] = events[events[MATCH_ID]==match_id]

    store["matches"] = load_matches_as_df(country).drop_duplicates(WY_ID)
    store["players"] = load_players_as_df().drop_duplicates(WY_ID)

    teams = load_teams_as_df()
    teams = teams[teams['type'] == 'club']
    teams = teams[teams['area'].apply(lambda area: area['name'] == country)]
    store["teams"] = teams

**Comment by agdhruv** [comment]
> Seeing how the soccerlog data set is probably going to be pretty important for many future soccer analytics researchers, I will try to add a converter to `socceraction` as soon as possible.

Hi @TomDecroos is there any update on this? I'd like to use the Wyscout open dataset to convert data to SPADL.

@kkoripl Where can I find the code that worked for you?

**Comment by probberechts** [comment]
@agdhruv I've added [a notebook](https://github.com/ML-KULeuven/socceraction/blob/wyscout_support/public-notebooks/EXTRA-load-and-convert-wyscout-data.ipynb) which downloads and converts the Wyscout dataset to the SPADL format in the `wyscout_support` branch.  If you use it, you should be aware that there are still some bugs in the wyscout converter (see other issues).

**Comment by derwidii** [comment]
Hi! I have the same issue using wyscout data. The data is provided in the following format: match-1.json, match-2.json, match-3.json, and so on. Hence, i cannot convert the data into the SPADL format.

Nevertheless, I'd like to use the socceraction package. It seems that your notebook that has been provided back then is not available anymore. Is there another workaround by now? Thank you in advance.
