### ISSUE TITLE
Data leak in expected goals model

### ISSUE THREAD

**Issue by anilcemarslan** [ML-KULeuven/socceraction#15]
Hi!

First of all, thanks for the great package, it makes working with JSON files much easier!

I was reviewing the latest expected goal model code (EXTRA-build-expected-goals-models) and I think there is a small data leak in the model.

Features dx_a0 and dy_ao (also the movement_a0 as it is derived from other 2) uses end location information of the action, for shots this becomes the end location of the shot. All the successful (goal) shots have end x location either 0 or 105 (30-37 for y values) - so movement information actually inherits the result of the shot in it. For example, if the shot is taken from 25 (start_x_a0 = 25) meters horizontal distance away from the goal, any value less than 25 dx_a0 would automatically mean that the shot was not a goal. It is not a direct leak but still, I believe the model would be better without these features in it. 

Please let me know if I'm missing a point!

Best wishes!

**Comment by TomDecroos** [comment]
Hi! Thanks for noticing this. You are absolutely correct about the information leakage. I have solved this issue with this commit: https://github.com/ML-KULeuven/socceraction/commit/511a6aa04fc041253bf750b11b5cdd485123c6ae
