### ISSUE TITLE
Minutes played by a player in a game is wrong using the PublicWyscoutLoader class

### ISSUE THREAD

**Issue by BWyckaert** [ML-KULeuven/socceraction#153]
The `_get_minutes_played` method uses the timestamps of events in a single game to determine the length of that game and thus how long players played. 

https://github.com/ML-KULeuven/socceraction/blob/e7bc0d0d382852674089d85f0a29a45e2b84bbb8/socceraction/data/wyscout/loader.py#L726-L733

The `players` method in the PublicWyscoutLoader however,  passes all the events in the competition of a game, instead of the events in the game itself.

https://github.com/ML-KULeuven/socceraction/blob/e7bc0d0d382852674089d85f0a29a45e2b84bbb8/socceraction/data/wyscout/loader.py#L286-L290

This causes all games in the same competition to have the same length and the minutes played for all players to be wrong. As a temporary solution, replacing line 290 with the following 2 lines fixes the issue (but I don't know if it's the most efficient way to do it):
```python
match_events = filter(lambda event: event['matchId'] == game_id, self.get(path_events))
mp = _get_minutes_played(lineups, cast(List[Dict[str, Any]], match_events))
```

**Comment by probberechts** [comment]
Hi @BWyckaert, thanks for pointing this out! It should be fixed in the latest commit.
