### ISSUE TITLE
manual running of tests/datasets/download.py required for tests

### ISSUE THREAD

**Issue by znstrider** [ML-KULeuven/socceraction#167]
For the testing suite to succeed, it seems we need to manually run tests/datasets/download.py multiple times with all of "statsbomb", "wyscout", "convert-statsbomb" and "convert-wyscout" args.

As is this should probably at least be mentioned in the contributing guide. Or can this be automated when running nox?

Further the main function errors out if no further arg is provided. How should the logic be here?

```python
if __name__ == '__main__':
    if len(sys.argv) == 1 or sys.argv[1] == 'statsbomb':
        download_statsbomb_data()
    if sys.argv[1] == 'convert-statsbomb':
        convert_statsbomb_data()
    if len(sys.argv) == 1 or sys.argv[1] == 'wyscout':
        download_wyscout_data()
    if sys.argv[1] == 'convert-wyscout':
        convert_wyscout_data()
    if len(sys.argv) == 1 or sys.argv[1] == 'spadl':
        create_spadl(8657, 777)
```

**Comment by probberechts** [comment]
You indeed have to run the following commands before running the tests:

```bash
poetry run python tests/datasets/download.py statsbomb
poetry run python tests/datasets/download.py wyscout
```

These download the public StatsBomb and Wyscout datasets.

The other options are not needed if you just want to run the default tests:
 - The `convert-wyscout`,  and `convert-statsbomb` are only needed when you want to run the `e2e` but these are disabled by default.
- The `spadl` option allows you to recreate the data stored in `tests/datasets/spadl`. This data is also included in the git repository.

I agree that we should document this in the contributors guide. I'll also add a check to the nox file.

**Comment by znstrider** [comment]
> You indeed have to run the following commands before running the tests:
> 
> ```shell
> poetry run python tests/datasets/download.py statsbomb
> poetry run python tests/datasets/download.py wyscout
> ```
> 
Should I extend the contribution guide with this, or are you handling this?

**Comment by probberechts** [comment]
I'll take care of it. Thanks for pointing this out.
