### ISSUE TITLE
Bug in conversion of owngoals to atomic SPADL

### ISSUE THREAD

**Issue by BWyckaert** [ML-KULeuven/socceraction#198]
When converting SPADL actions to atomic SPADL actions, an owngoal is currently converted as follows: 

https://github.com/ML-KULeuven/socceraction/blob/8e29c57b3b7306a634f42bfb69ab6ad676e17067/socceraction/atomic/spadl/base.py#L119-L127

However, owngoals in SPADL are the result of a `bad_touch` and not of a `shotlike`, so owngoals are never correctly converted.

This can be fixed by replacing line 127 with:

```python
    owngoal = (actions.type_id == _spadl.actiontypes.index("bad_touch")) & (actions.result_id == _spadl.results.index('owngoal'))
```

**Comment by probberechts** [comment]
I think we can even drop the action type condition. The following should suffice:

```python
owngoal = (actions.result_id == _spadl.results.index('owngoal'))
```

Would you like to create a PR or is it easier if I quickly fix it myself?
