### ISSUE TITLE
Bug in conversion to atomic SPADL due to gaps in Wyscout data

### ISSUE THREAD

**Issue by BWyckaert** [ML-KULeuven/socceraction#199]
Wyscout collects its data by video analysis. This means that when replays of certain events are shown, the events that occur during that replay are not captured. The most common replayed events are goals and this occasionally causes the kick-off and subsequent actions to be absent from the game data. Most of the time this causes no issues (except for the fact that there is no data for small parts of the game), but when converting SPADL actions to atomic SPADL actions we run into problems. When converting from default SPADL to atomic SPADL, the result (`result_id` and `result_name`) are replaced by an extra action. For `shotlike` actions this is done as follows: 

https://github.com/ML-KULeuven/socceraction/blob/8e29c57b3b7306a634f42bfb69ab6ad676e17067/socceraction/atomic/spadl/base.py#L116-L166

In short: when the result of a `shot` action is success, the next action will be a `goal`, when the action following the shot is a `corner` or a `goalkick`, the next action will be `out`. The problem now lies in:

https://github.com/ML-KULeuven/socceraction/blob/8e29c57b3b7306a634f42bfb69ab6ad676e17067/socceraction/atomic/spadl/base.py#L156-L161

Due to some events not being registered by Wyscout after a goal, it is possible that the first event registered after a goal is a `goalkick` or a `corner`, instead of the expected `pass` (the kickoff). This means that line 161 will override what is done on line 159, causing the goals to be incorrectly converted.

There are two possible ways to fix this (that I've come up with at least):
- The first is to simply replace line 159 with line 161, changing the order of the masks.
- The second is to allow a maximum time difference between a shotlike action and a goalkick or corner for the goalkick or corner to be considered the action following the shot. However, considering e.g. VAR interventions, which might take some time to complete, this might be imprecise.

**Comment by probberechts** [comment]
Thanks for the detailed bug report! 

If I am not mistaken, the Wyscout event data has a custom event for these replays. Hence, the ideal long-term solution would be to rewrite the Atomic-SPADL converter to take the additional information in the event stream into account. I already planned to implement this anyway as it would also improve the timing of ball receipts and some other parts of the implementation.  

However, it might take a while before I find the time to work on this. Simply replacing line 159 with line 161 seems a good solution for now. I assume this happens very rarely, but it is indeed important that goals are registered correctly. Would you like to create a PR or is it easier if I quickly fix it myself?
