### ISSUE TITLE
Action positions are wrong when converting from Wyscout events

### ISSUE THREAD

**Issue by BWyckaert** [ML-KULeuven/socceraction#205]
Two mistakes are made when converting Wyscout events to SPADL events:

1) `make_new_positions` clips all x and y coordinates to (0, 105) and (0, 68) respectively, where 105 and 68 are the field width and field length used in the whole package. 

https://github.com/ML-KULeuven/socceraction/blob/3e267fb34c0afbed318eb5b1d8d802ed44ce5e58/socceraction/spadl/wyscout.py#L161-L182

The problem is that when this method is called, we are still working with Wyscout positions and Wyscout defines positions as follows: 

![image](https://user-images.githubusercontent.com/58517640/155366324-74b9c060-3595-4d04-8797-9dd9c02d57e8.png)

which I got from [https://figshare.com/articles/dataset/Events/7770599?backTo=/collections/Soccer_match_event_dataset/4415000](url). This means that either the positions have to be clipped to (0, 100) (both x and y) or they have to be clipped at a later stage. I don't know what's more desirable.

2) The second mistake is that line 47 in `convert_to_actions` fixes the direction of play (the players who makes the action always plays from left to right), but as can be seen in the picture above, Wyscout already has its events defined like this, so this line just reverts the process.

https://github.com/ML-KULeuven/socceraction/blob/3e267fb34c0afbed318eb5b1d8d802ed44ce5e58/socceraction/spadl/wyscout.py#L25-L52

**Comment by probberechts** [comment]
The first one was indeed a bug that I introduced recently. I'll push a fix in a couple of minutes.

The second one is intended behaviour. In SPADL we use the "home team always attacks to the right" convention, which is most convenient when visualising actions. I checked it, and that seems to be right for the Wyscout data (at least the public one). The docs incorrectly say that
> The direction of play corresponds to the direction in the original event stream data

I'll make sure to change that.

You can convert the direction with the [play_left_to_right()](https://socceraction.readthedocs.io/en/latest/modules/generated/socceraction.spadl.play_left_to_right.html#socceraction.spadl.play_left_to_right) function such that the lower x-coordinates represent the own half of the team performing the action

Thanks for your ongoing debugging efforts!

**Comment by BWyckaert** [comment]
Thank you for clarifying. I assumed the VAEP model was trained on action positions as they are now, but I didn't see that there is also a `play_left_to_right()` function that is applied on the features themselves. 

https://github.com/ML-KULeuven/socceraction/blob/f95de77e6089ee160f62b1a6815461f010e3de47/socceraction/vaep/features.py#L92
