### ISSUE TITLE
Error with function add_players_and_teams in statsbomb.py

### ISSUE THREAD

**Issue by davidfombella** [ML-KULeuven/socceraction#21]
Hi all

I am trying to execute notebook 2 of tutorial and it is failing on this function

**def add_players_and_teams(lineups_url, h5file):**
 on this line   
**players = pd.DataFrame(players.values())**

 DataFrame constructor not properly called!

![Captdddura](https://user-images.githubusercontent.com/2682459/72509091-1dae0a00-3847-11ea-9c84-261ff3a9f6bc.PNG)

Regards

**Comment by TomDecroos** [comment]
Hi David,

I just mentioned to you on twitter that updating your pandas installation should fix this. Can you let me know if this indeed fixed the issue? :-)

Cheers,
Tom

**Comment by davidfombella** [comment]
just works after upgrading...now stuck with next cell
