### ISSUE TITLE
Error in inspect hdf file

### ISSUE THREAD

**Issue by davidfombella** [ML-KULeuven/socceraction#22]
After trying to reaad hdf file on notebook 2 i get this error maybe a version package issue, Thanks in advance

![imagen](https://user-images.githubusercontent.com/2682459/72512713-7e8c1100-384c-11ea-9b49-cccdd9136232.png)

![error !](https://user-images.githubusercontent.com/2682459/72512856-b5fabd80-384c-11ea-8886-3bb2c6d7fa96.PNG)

refading it could be a numpy issue ... any solution?
This is my numpy version
>>> np.__version__
'1.16.4'

**Comment by TomDecroos** [comment]
`pandas` uses the `tables` package to read and write from hdf5-files. Maybe try upgrading that package as well?
`pip install tables --upgrade`

**Comment by davidfombella** [comment]
Solved thanks! after upgrading tables it worked
