### ISSUE TITLE
xG example: remove movement_a0 from features

### ISSUE THREAD

**Issue by denisov-vlad** [ML-KULeuven/socceraction#223]
In [xG model example](https://github.com/ML-KULeuven/socceraction/blob/master/public-notebooks/EXTRA-build-expected-goals-model.ipynb) you use `movement_a0` feature which is highly correlated with classification result and breaks other features importances.

I've tested the model with and without it and compared with Understat data. With this feature you have good values for goals but other shots from good positions have small probabilities.

Of course AUC score will decrease to ~ 0.83 (tested with XGBoost / LightGBM models) but final result for each shot seems more accurate.

**Comment by probberechts** [comment]
Yes, that feature should be removed. It leaks post-shot information, as it is based on the shot's end coordinates.

FYI, we have a much better xG model here: https://github.com/ML-KULeuven/soccer_xg
