### ISSUE TITLE
Bug in _get_minutes_played

### ISSUE THREAD

**Issue by BWyckaert** [ML-KULeuven/socceraction#228]
The `_get_minutes_played `method in [wyscout loader](https://github.com/ML-KULeuven/socceraction/blob/master/socceraction/data/wyscout/loader.py) contains 2 bugs:

1) The duration of a game is defined as follows: 

https://github.com/ML-KULeuven/socceraction/blob/597485744cf90ff44648723f0662ee9c3829db85/socceraction/data/wyscout/loader.py#L731-L735

In words: take the time in seconds of the last event in every period, convert to minutes and sum up the values. This means that injury time is taken into account for every period. Wyscout, however, only takes into account injury time of the last period of the game when  defining the minute of e.g. a substitution, a red card. So when you now define the amount of minutes played of a substitute as follows:

https://github.com/ML-KULeuven/socceraction/blob/597485744cf90ff44648723f0662ee9c3829db85/socceraction/data/wyscout/loader.py#L764

and the time played by a player who gets substituted as:

https://github.com/ML-KULeuven/socceraction/blob/597485744cf90ff44648723f0662ee9c3829db85/socceraction/data/wyscout/loader.py#L768

the  amount of minutes played will be too high and too low respectively. For players who play a full game there is obviously no problem.

2) Red cards are not taken into account, so a player who gets a red card in e.g. minute 5 will get his minutes played set to the duration of the game.

**Comment by probberechts** [comment]
Another great catch! Thanks, Bram.
A pull request would be welcome if you have a fix.

I think the same bug exists in the other data loaders too. I'll look into this.

**Comment by probberechts** [comment]
The problem exists in all data loaders. 

- [x] Wyscout loader (fixed in f5173e637dcfdfc40b58b862327bc30fd4258742)
- [ ] StatsBomb loader
- [ ] WhoScored loader
- [ ] F7 XML loader
- [ ] F9 JSON loader
- [ ] MA1 JSON loader
- [ ] MA3 JSON loader
