### ISSUE TITLE
Different output for xT values and visualizations in the 'EXTRA-run-xT.ipynb' notebook

### ISSUE THREAD

**Issue by shua53** [ML-KULeuven/socceraction#237]
When running the 'EXTRA-run-xT.ipynb' notebook under the 'public-notebooks' folder, I got a completely different output for xT values and thus different visualizations as follows. 

![image](https://user-images.githubusercontent.com/33623623/159827792-497dc435-3ec8-46eb-b062-d104e02f9b01.png)

![image](https://user-images.githubusercontent.com/33623623/159826154-8b50dfaa-d60e-4bda-915d-a08969162f83.png)

As guided, I ran the '1-load-and-convert-statsbomb-data.ipynb' notebook first. I noticed that there are some changes for the StatsBomb dataset, but I don't think it is the reason resulting in the completely different output. I am using Python 3.7.2 and socceraction 1.2.2.

**Comment by probberechts** [comment]
Thanks for reporting this! It should be fixed in master. Until the next pip release, you can also fix it by simply resetting the index of the input dataframe: ``xTModel.rate(A.reset_index())``
