### ISSUE TITLE
Remove off the ball foul events (Wyscout)

### ISSUE THREAD

**Issue by BWyckaert** [ML-KULeuven/socceraction#240]
Wyscout considers a few off the ball fouls, namely `Out of game foul`, `Protest` and arguably `Late card foul` (these are the `subEventName`'s). When converting Wyscout events to SPADL actions, these aren't removed. This causes VAEP-models to make some very inaccurate predictions in certain situations. 

1) Atomic models

Using an XGBoost model trained on atomic SPADL actions, consider a sequence of actions starting 2 actions before a `penalty_shot` until 1 action after the `penalty_shot`. In a normal situation these actions get VAEP-values similar to the following:

![image](https://user-images.githubusercontent.com/58517640/159964789-c9759c96-3f83-4016-a4bb-bdd1f0a49486.png)

The model gives the second action a very negative value, because it has learned that fouls with certain x and y values (within the penalty area) very often result in a goal for the opponent.

Now consider the following sequence of actions:

![image](https://user-images.githubusercontent.com/58517640/159965605-49c25432-a1d0-4e3e-ad36-a419aeeee8b0.png)

The first foul is the one that causes the penalty, the second one is a yellow card for protest. The first foul correctly gets a very negative value, but the second foul get a very positive value. The model has probably learned that two consecutive fouls result in a scoring/conceding chance of around 0 (which is true in almost all cases), so `-(concedes - prev_concedes)` results in a high value. This in turn results for a weird value for the `shot_penalty` and following action as well.

https://github.com/ML-KULeuven/socceraction/blob/b620b4038310627e40aca98e6e72c34ff6d70f9c/socceraction/vaep/formula.py#L114

2. Non-atomic models

Consider again the second sequence of actions, but now with a non-atomic model:

![image](https://user-images.githubusercontent.com/58517640/159973906-6b87d625-ab9a-482a-85cf-1be49094c309.png)

Here the opposite occurs: the protest foul gets a very negative value. My guess for this result would be that the non-atomic models consider the result of the actions themselves to be more important than the previous 2 actions, whereas for the atomic models there is no result. In this case, the value for the `shot_penalty` itself is correct (because the chance that a penalty is scored is hard-coded).

**Comment by probberechts** [comment]
If I am not mistaken, Wyscout has the following subtypes for fouls:

type_id | subtype_id | label
-- | -- | --
2 | 20 | [Foul](https://dataglossary.wyscout.com/foul/)
2 | 21 | [Hand foul](https://dataglossary.wyscout.com/hand_foul)
2 | 22 | [Late card foul](https://dataglossary.wyscout.com/late_card_foul/)
2 | 23 | [Out of play foul](https://dataglossary.wyscout.com/out_of_play_foul)
2 | 24 | [Protest](https://dataglossary.wyscout.com/protest_foul)
2 | 25 | [Simulation](https://dataglossary.wyscout.com/offensive_duel)
2 | 26 | [Time lost foul](https://dataglossary.wyscout.com/time_lost_foul/)
2 | 27 | [Violent Foul](https://dataglossary.wyscout.com/violent_foul)
2 | ? | [Penalty Foul](https://dataglossary.wyscout.com/penalty_foul/)


The  "Out of play foul" and "Protest"  events should indeed be converted to `non_action` in SPADL. I believe the "Time lost fouls" should be excluded too, as these do not result in a change of possession. You can add an extra condition in the line below https://github.com/ML-KULeuven/socceraction/blob/5fd6bd7e29df8d230103d586f8f9449bdb0ca500/socceraction/spadl/wyscout.py#L593

```py
... and (event["subtype_id"] not in [23, 24, 26])
```

I am not sure what to do with "Late card foul",  "Simulation", and "Violent foul". 

I've noticed that the StatsBomb converter keeps fouls that have advantage played (e.g., "Late card foul") as regular fouls. I do not think that is ideal though. We could keep these and set the outcome to "failed" or record them as a failed tackle. However, maybe Wyscout already records both a tackle and a foul in such cases, which means that the "Late card foul" event can be dropped. 

I think we should convert "Simulation" fouls to a failed `dribble` or `take_on`, as it's losing the ball that changes the possession value.

I am not sure what a `violent foul` exactly constitutes. I guess these can both happen during (e.g., giving an elbow during a duel) and out of play (e.g., punching a player as a reaction to a previous foul). The former should be kept in SPADL, the latter should be converted to a non-action.

What is your opinion about this? Would you like to work on a PR?

**Comment by BWyckaert** [comment]
1. Late card foul

It looks like Wyscout only records the `Late card foul` and not the tackle which caused it. The Wyscout converter then converts this to a regular foul. I have however just noticed that the position Wyscout uses for these `Late card foul`s is the position where the card is given to the player and not the position where the tackle was executed. If this card is given within the players own penalty area, this makes VAEP-models think that the foul caused a penalty, giving it a very negative value. Unless you would know of a workaround, I would remove these.

2. Simulation

Converting `Simulation`s to a failed `take_on` seems like a good idea to me. In a lot of cases, however, a foul by `Simulation` is already preceded by a failed `take_on`. In this case I think we can just remove the `Simulation`?

3. Violent foul

Wyscout defines a `Violent foul` as follows:

"_Some violent action, kicks or punches without the ball, or very bad tackles, when the player is risking to injure his opponent._"

I guess this could include both during and out of play, but I don't see any way to differentiate them so I would leave these in.

**Comment by probberechts** [comment]
Thanks for checking!

So, we leave out "Out of play foul", "Protest", "Time lost foul" and "Late card foul". 

For a "Simulation", we check if the preceding event was a take-on or a dribble. If so, we set the outcome to "failed" and drop the "Simulation". Otherwise, we replace the "simulation" with a failed dribble.

For "Violent fouls" it is still unclear whether they can happen out of play. We could check whether they happen after another foul, the ball going out, ... However, I think we can assume they always happen in-play for know. Just something to keep in mind.

All other fouls are converted to a foul in SPADL without modification.

**Comment by probberechts** [comment]
Thanks! I was thinking that a player might also dive if he senses a defender in his back. Hence why I proposed a `dribble`.
