### ISSUE TITLE
Wyscout convertor discards own goals from touch events

### ISSUE THREAD

**Issue by probberechts** [ML-KULeuven/socceraction#25]
## Bug

Own goals resulting from bad touch events in the Wyscout event streams are missing in the SPADL representation.

## Minimal example

As a minimal example, here is an own goal from the game between Leicester and Stoke on 24 Feb 2018. Stoke's goalkeeper Jack Butland allows a low cross to bounce off his gloves and into the net:
|        | eventId | subEventName | tags                                               | playerId | positions                                         | matchId | eventName          | teamId | matchPeriod | eventSec            | subEventId | id        |
|--------|---------|--------------|----------------------------------------------------|----------|---------------------------------------------------|---------|--------------------|--------|-------------|---------------------|------------|-----------|
| 466559 | 8       | Cross        | "\[\{'id': 402\}, \{'id': 801\}, \{'id': 1802\}\]" | 8013     | "\[\{'y': 89, 'x': 97\}, \{'y': 0, 'x': 0\}\]"    | 2499994 | Pass               | 1631   | 2H          | 1496 | 80         | 230320305 |
| 466560 | 7       | Touch        | \[\{'id': 102\}\]                                  | 8094     | "\[\{'y': 50, 'x': 1\}, \{'y': 100, 'x': 100\}\]" | 2499994 | Others on the ball | 1639   | 2H          | 1497 | 72         | 230320132 |
| 466561 | 9       | Reflexes     | "\[\{'id': 101\}, \{'id': 1802\}\]"                | 8094     | "\[\{'y': 100, 'x': 100\}, \{'y': 50, 'x': 1\}\]" | 2499994 | Save attempt       | 1639   | 2H          | 1499 | 90         | 230320135 |

[--> Download source](https://github.com/ML-KULeuven/socceraction/files/4414324/wy_events.txt)

And the corresponding SPADL representation:
|   | game\_id   | period\_id | time\_seconds       | team\_id | player\_id | start\_x            | start\_y | end\_x              | end\_y | bodypart\_id | type\_id | result\_id |
|---|------------|------------|---------------------|----------|------------|---------------------|----------|---------------------|--------|--------------|----------|------------|
| 0 | 2499994\.0 | 2\.0       | 1496 | 1631\.0  | 8013\.0    | 101\.85             | 7\.48    | 0\.0                | 68\.0  | 0            | 1        | 0          |
| 1 | 2499994\.0 | 2\.0       | 1499 | 1639\.0  | 8094\.0    | 1\.05  | 34\.0    | 1\.05  | 34\.0  | 2            | 14       | 1          |

The `result_id` of the second action should be 3 (= own_goal).

**Comment by SlavCzar** [comment]
Which wyscout converter did you use? the wyscout open log data that i have does not contain some of the json keys which are required by the converter in wyscout.py

**Comment by probberechts** [comment]
I fixed this in 6c17edd, but one minor issue remains for the example above: SPADL adds a dribble action between the bad touch (the own goal) of the goalkeeper and his last attempt to save the ball before it crosses the line. Maybe adding the dribble there is not the most appropriate thing to do, but is an edge case that can be ignored in my opinion.
