### ISSUE TITLE
original_event_id is sometimes returning 'nan'. 

### ISSUE THREAD

**Issue by michaelpulis-UOM** [ML-KULeuven/socceraction#283]
When using the open data from Statsbomb, about 2-3% of each action's original event id fields are returning nan. Can this be resolved ?

**Comment by probberechts** [comment]
SPADL [adds dribbles](https://github.com/ML-KULeuven/socceraction/blob/f15324269db478fc98d840b86869ba2c9ea083dd/socceraction/spadl/base.py#L38) (which are carries in StatsBomb's terminology) to fill up gaps between events. As these are not in the original event data, they obviously do not have an `original_event_id`.
