### ISSUE TITLE
Exception in socceraction.atomic.spadl.convert_to_atomic method

### ISSUE THREAD

**Issue by flijer** [ML-KULeuven/socceraction#31]
NameError                                 Traceback (most recent call last)
<ipython-input-24-d7151d67d65d> in <module>
     12     player_games.append(statsbomb.extract_player_games(events))
     13     actions = statsbomb.convert_to_actions(events,match.home_team_id)
---> 14     atomic_actions[match.match_id] = atomicspadl.convert_to_atomic(actions)
     15 
     16 games = matches.rename(columns={"match_id":"game_id"})

C:\ProgramData\Anaconda3\envs\datasciencesoccer-RQVybP6P\lib\site-packages\socceraction\atomic\spadl.py in convert_to_atomic(actions)
     36 def convert_to_atomic(actions):
     37     actions = actions.copy()
---> 38     actions = extra_from_passes(actions)
     39     actions = add_dribbles(actions)  # for some reason this adds more dribbles
     40     actions = extra_from_shots(actions)

C:\ProgramData\Anaconda3\envs\datasciencesoccer-RQVybP6P\lib\site-packages\socceraction\atomic\spadl.py in extra_from_passes(actions)
    113     extra["result_id"] = -1
    114 
--> 115     offside = prev.result_id == results.index("offside")
    116     out = ((nex.type_id == actiontypes.index("goalkick")) & (~same_team)) | (
    117         nex.type_id == actiontypes.index("throw_in")

NameError: name 'results' is not defined

**Comment by TomDecroos** [comment]
Thanks for reporting this bug!
This commit should have fixed it : https://github.com/ML-KULeuven/socceraction/commit/cb05c3adb2d3d236ad6a282b7c18cbd9bda0d62a

Try upgrading to socceraction 0.2.1 using `pip install socceraction --upgrade`
