### ISSUE TITLE
How is a dribble that leads to possession loss modelled?

### ISSUE THREAD

**Issue by michaelpulis-UOM** [ML-KULeuven/socceraction#313]
Hi, I would like to ask about how dribbles that lead to possession loss are encaptured. In the documentation it states that dribble is always successful. What about the case where a player starts a dribble and is stopped halfway?

**Comment by probberechts** [comment]
"dribbles" in socceraction are by definition actions that are never interrupted. They correspond to "carries" in StatsBomb data and "touches" in Wyscout data and describe a player possessing the ball at their feet, either moving with the ball or standing
still. Dribbles that attempt to get past a defender are called "take ons". These can fail.

**Comment by probberechts** [comment]
It depends on what you want to do with it. I think a "dribble" and a "take-on" (I am using the socceraction definitions here) are distinct action types. The former are usually just ball touches without any pressure of a defender, the latter are challenging actions that can provide a lot of value. If you merge them, you'll notice that some players that have a lot of ball touches (e.g., central defenders) will emerge as great dribblers.

**Comment by michaelpulis-UOM** [comment]
Understood. Thanks for this feedback, I will proceed with your comments in mind.
