### ISSUE TITLE
Unable to download socceraction.vaep

### ISSUE THREAD

**Issue by chrisamansker** [ML-KULeuven/socceraction#345]
Hi there, 

I'm getting an error when I try to download and initialize the .vaep on Mac OS. I am running on Python 3.9.7, and was wondering if socceraction was able to use that version?

Thanks!

Chris Mansker

**Comment by probberechts** [comment]
Yes, socceraction support Python >=3.7.1,<3.11.

I cannot help you without any details about the error. Hence, could you provide the stacktrace and tell me what I should do to reproduce it?
