### ISSUE TITLE
 AttributeError: module 'socceraction.spadl' has no attribute 'add_names'

### ISSUE THREAD

**Issue by laradigital** [ML-KULeuven/socceraction#353]
Hi, could u help me plz!

I get this error when run this script : https://github.com/ML-KULeuven/socceraction/blob/master/public-notebooks/EXTRA-run-xT.ipynb

![image](https://user-images.githubusercontent.com/93475313/181238019-b11e628e-06ed-4e06-8094-22319cd62429.png)

**Comment by probberechts** [comment]
Maybe you are using an old version of socceraction? What is the output of 
```py
import socceraction
socceraction.__version__
```

**Comment by laradigital** [comment]
I can't check the version! 

AttributeError: module 'socceraction' has no attribute '__version__'

**Comment by probberechts** [comment]
You forgot the underscores in `socceraction.__version__`

**Comment by laradigital** [comment]
the version is '1.2.3'

**Comment by probberechts** [comment]
Ok. That is the latest version and everything seems to work when I try to run it. Maybe try with a minimal example to debug the problem. What do you get if you run

```py
import socceraction.spadl as spadl
print(spadl.add_names)
print(dir(spadl))
```
