### ISSUE TITLE
Meaning of nb_prev_actions=0?

### ISSUE THREAD

**Issue by michaelpulis-UOM** [ML-KULeuven/socceraction#359]
I am using the VAEP and Atomic-VAEP Implementations. To confirm that I am understanding the implementation correctly, I set the `nb_prev_actions` parameter to be 0, expecting the system to fail. However, it still ran and trained correctly. So I would like to ask for clarification.

When I set the `nb_prev_actions` to `n`, and tell the model to rate the value of the actions in a match, does the model make use of `n` total actions to make the prediction, or `n+1` actions? If it uses `n` actions to make the prediction, then what does it mean to have `nb_prev_actions = 0`?

Thanks

**Comment by probberechts** [comment]
If you set the `nb_prev_actions` parameter to `n`, and tell the model to rate the value of the actions in a match, the model makes use of `n` total actions to make the prediction. The idea is that each action changes the game state. For example, if  you have a sequence $PASS \rightarrow s_1 \rightarrow DRIBBLE \rightarrow s_2 \rightarrow TACKLE \rightarrow s_3$ and `nb_prev_actions = 2` then the features for game state $s_3$ are based on the attributes of the tackle and dribble.

If you look at [the implementation](https://github.com/ML-KULeuven/socceraction/blob/947ef2a280b0f7c6d080ab5ffdacfd32ea153e66/socceraction/vaep/features.py#L62) you can see that values for `nb_prev_actions < 1` are handled identically to `nb_prev_actions = 1`. Hence, if you set the `nb_prev_actions` parameter to be 0, you actually compute the features based on one preceding action.

I agree that it would be better to raise an exception though. I'll adapt that.

**Comment by michaelpulis-UOM** [comment]
That makes sense! 

The way you explained it is the way I thought it worked, but when it didn't fail when I set `nb_prev_actions` to 0 confused me. I agree that it should raise an error.

Thanks
