### ISSUE TITLE
Lack of compatibility with Wyscout's Soccer-logs open dataset

### ISSUE THREAD

**Issue by rbun013** [ML-KULeuven/socceraction#36]
Hi @probberechts , where can I find the EXTRA-load-and-convert-wyscout-data.ipynb notebook? The link below is no longer working. Thank you

@agdhruv I've added [a notebook](https://github.com/ML-KULeuven/socceraction/blob/wyscout_support/public-notebooks/EXTRA-load-and-convert-wyscout-data.ipynb) which downloads and converts the Wyscout dataset to the SPADL format in the `wyscout_support` branch.  If you use it, you should be aware that there are still some bugs in the wyscout converter (see other issues).

_Originally posted by @probberechts in https://github.com/ML-KULeuven/socceraction/issues/14#issuecomment-621434442_

**Comment by probberechts** [comment]
There is now [a custom loader](https://github.com/ML-KULeuven/socceraction/blob/752664886700d24615eb9bd81c96feb93c8d23ba/socceraction/spadl/wyscout.py#L18) for the soccer-logs dataset, similar to the `StatsbombLoader`.

Note that the pip version lags behind, so you will have to install the package from Github to use this feature.
