### ISSUE TITLE
Adding R xThreat Implementation

### ISSUE THREAD

**Issue by gkrhines** [ML-KULeuven/socceraction#39]
This repo did wonders for me when I was trying to wrap my head around the mathematics behind Karun Singh's Expected Threat model. As someone who is much more comfortable with R instead of Python, I actually ended up converting xthreat.py to an RScript. That file can be found [here](https://github.com/gkrhines/xThreatR).

If your group wanted to add that script (which is SPADL compatible) to your repository, I would have no reservations. I think it would allow the Expected Threat model to become more accessible. 

Thanks for your work!

**Comment by probberechts** [comment]
Thanks for your kind words and sharing your implementation. However, I would rather avoid the added cost of having to maintain multiple versions. Therefore, I prefer to keep the code in this repository Python-only. Maybe you can merge your code with [Rteta](https://github.com/RobWHickman/Rteta)? This repository already contains R-implementations of SPADL and VAEP.
