### ISSUE TITLE
Add kloppy as reader

### ISSUE THREAD

**Issue by koenvo** [ML-KULeuven/socceraction#41]
First of all: thanks for this great library!

I was wondering what is needed to add kloppy as a reader for input files. When kloppy can be used users of socceraction can easily switch to other formats supported by kloppy (like Sportec).

Challenges:
- What attributes are required for socceraction to work, and is kloppy (at this moment) able to provide all those?
- Same question but than for future development

Curious what you think about this. If it seems doable I can start working on a PR for socceraction.

**Comment by probberechts** [comment]
I have to admit that outsourcing the implementation of additional convertors to Kloppy appeals to me 😉. Basically, this means that Kloppy should provide a standardized data model for each provider from which we can infer all attributes used in the SPADL format.

First, you would need a Kloppy event type (with a standardized definition between providers) for each SPADL action. I had a quick look at the event types in Kloppy's docs and it seems that there is already an event type (or event type + qualifiers) for most actions:

| SPADL action     | Kloppy EventType                                            |
|------------------|-------------------------------------------------------------|
| pass             | PASS                                                        |
| cross            | PASS + PassQualifier:CROSS                                  |
| throw_in         | PASS + SetPieceQualifier:THROW_IN                           |
| freekick_crossed | PASS + PassQualifier:CROSS + SetPieceQualifier:FREE_KICK    |
| freekick_short   | PASS + !PassQualifier:CROSS + SetPieceQualifier:FREE_KICK   |
| corner_crossed   | PASS + PassQualifier:CROSS + SetPieceQualifier:CORNER_KICK  |
| corner_short     | PASS + !PassQualifier:CROSS + SetPieceQualifier:CORNER_KICK |
| take_on          | TAKE_ON                                                     |
| foul             | FOUL_COMMITTED                                              |
| tackle           |                                                             |
| interception     | RECOVERY                                                    |
| shot             | SHOT                                                        |
| shot_penalty     | SHOT + SetPieceQualifier:PENALTY                            |
| shot_freekick    | SHOT + SetPieceQualifier:FREE_KICK                          |
| keeper_save      |                                                             |
| keeper_claim     |                                                             |
| keeper_punch     |                                                             |
| keeper_pick_up   |                                                             |
| clearance        |                                                             |
| bad_touch        |                                                             |
| non_action       | /                                                           |
| dribble          | CARRY                                                       |
| goalkick         | PASS + SetPieceQualifier:GOAL_KICK                          |

Goalkeeper actions still seem to be missing (but that does not matter a lot for valuing actions) and I could not find something that maps to tackles, clearances and bad touches. Also, I do not know to what extend these event types and qualifiers are implemented for each provider. For example, the PASS_TYPE seems to be missing in the StatsBomb serializer.

Furthermore, we should be able to get the following attributes from the `kloppy.domain.models.event.Event`:

- [x]    game_id
- [x]    original_event_id
- [x]    period_id
- [x]    time_seconds
- [x]    team_id
- [x]    player_id
- [x]    start_x
- [x]    start_y
- [x]    end_x
- [x]    end_y
- [ ]   bodypart_id: ['foot', 'head', 'other', 'head/other']
- [X]    result_id: [ 'fail',  'success', 'offside', 'owngoal', 'yellow_card', 'red_card']

This seems to be pretty complete already. Only for bodypart, we are missing a "other" type. I think we can infer everything else from the Event object (or the previous/next Event in the dataset). 

Once these additional event types are added to Kloppy, it should be relatively easy to add a function
```python
socceraction.spadl.kloppy.convert_to_actions(
    events: kloppy.domain.models.event.EventDataset, 
    home_team_id: int
) -> DataFrame[socceraction.spadl.base.SPADLSchema]
```

**Comment by koenvo** [comment]
Great to hear you like the idea. Also really nice you already did a comparison, which indeed looks promising.

I created an overview for what is implemented right now per provider: https://kloppy.pysport.org/providers/ . There are clearly some parts missing. I should update the overview to differentiate between not supported by a) kloppy or b) provider. 

They both require different actions:
a) Implement at kloppy side
b) Add flags to Dataset (kloppy side) to indicate missing data, and fill at socceraction side

Can you have a look at the table and see what at least needs to be implemented at the kloppy side?

**Comment by probberechts** [comment]
Nothing **has** to be implemented at the Kloppy side, since the original events can still be retrieved from the Kloppy Event, but I would rather not implement another version of the StatsBomb, Wyscout and Opta converters at the side of socceraction that extract half of the attributes from the Kloppy Event's fields and the other half from the original events. If we implement this, we should be able to use the same code for all kinds of Kloppy EventDatasets (or at least 95% of it), irrespective of the data source. 

This means that Kloppy would have to support:
1. A data model for tackles
2. A data model for clearances
3. A data model for bad touches
4. A data model for keeper actions
5. Implement the pass type qualifiers for each provider
6. Implement the bodypart qualifiers for each provider + add 'head' and 'other' qualifiers

It does not really matter how these are implemented. For example, tackles could be implemented as a new event type or as a  qualifier of the Recovery event. As long as we can infer all action types and the results from the standardized data model, it's fine.

**Comment by koenvo** [comment]
I created a milestone at the kloppy side: https://github.com/PySport/kloppy/milestone/1

Will add all issues there

**Comment by koenvo** [comment]
Last even types are merged, and released in version 3.13.0.

Is there anything I can help with?

**Comment by probberechts** [comment]
Converting from StatsBomb -> kloppy -> SPADL is now supported! 🎉

```python
from kloppy import statsbomb
from socceraction.spadl.kloppy import convert_to_actions
import socceraction.atomic.spadl as atomicspadl

dataset = statsbomb.load_open_data(match_id=8657)
spadl_actions = convert_to_actions(dataset, game_id=8657)
atomic_spadl_actions = atomicspadl.convert_to_atomic(spadl_actions)
```

This will also work for other data sources, but the resulting SPADL representation will be incomplete / contain errors. A bit more work is required on the kloppy-side to implement the full data model and resolve bugs.

**Comment by koenvo** [comment]
Awesome work Pieter! Really a huge step!
