### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by mepwang** [ML-KULeuven/socceraction#421]
it seems no particular dependencies to prevent socceraction running on python 3.11,
why not change pyproject.toml to move on python 3.11?

**Comment by probberechts** [comment]
Both [Numpy](https://numpy.org/doc/stable/release/1.22.0-notes.html) and [Pandas](https://pandas.pydata.org/docs/getting_started/install.html) do not yet seem to support Python 3.11.

**Comment by mepwang** [comment]
Numpy/pandas/scipy/scikit-learn/matplotlib already support python 3.11.

**Comment by probberechts** [comment]
Where do you find that? For example for the latest stable release of Pandas, both the [documentation](https://pandas.pydata.org/docs/getting_started/install.html) and [pypi](https://pypi.org/project/pandas/) do not list Pyhton 3.11 as a supported version.

**Comment by mepwang** [comment]
sorry my mistake ;)
pandas is installed and running on my python 3.11 environment so i thought pandas' migrated to 3.11
