### ISSUE TITLE
Opta data never converts to goalkick SPADL action

### ISSUE THREAD

**Issue by JeroenClijmans1** [ML-KULeuven/socceraction#45]
When converting Opta event stream data, there is never a conversion to a 'goalkick' SPADL action.

To do so, the _get_type_id function in opta.py needs to be changed. According to [this](https://github.com/fluidpixel/RePlayed/wiki/OPTA-Qualifiers#goalkeeper) source (couldn't find an up-to-date official document on the internet), a goal kick corresponds to pass qualifier 124.

Another question also arises: is a keeper throw (qualifier 123) also considered a goal kick in terms of SPADL actions. I think it makes sense to either have separate SPADL actions for these two, or one (renamed?) SPADL action for them both. I do not think that a keeper throw should be considered a regular pass, since there is no pressure on the keeper to execute this action quickly (in contrast to a regular pass). Therefore it may need a different treatment when processing the data.

**Comment by probberechts** [comment]
Thanks! Good catch. The goalkicks should be fixed in e639437. I'll make the discussion about keeper throws part of #37.
