### ISSUE TITLE
Missing events whith OptaLoader

### ISSUE THREAD

**Issue by Zapotnik** [ML-KULeuven/socceraction#459]
My data source : JSON from WhoScored
In the OptaEventSchema, it says the Pandas DataFrame should include "assist" and "keypass".
But they are missing.

Another minor issue : "goal" and "shot" are inverted.

**Comment by probberechts** [comment]
The "assist" and "keypass" fields are marked as optional in the schema. They are not (explicitly) included in WhoScored's JSON format, but I think it should be possible to extract them from the qualifiers. Feel free to create a pull request if you want to add them.

Good catch wrt the inverted columns. I will fix that.
