### ISSUE TITLE
WhoScored Parser Not Working DateTime Error

### ISSUE THREAD

**Issue by raaghule** [ML-KULeuven/socceraction#474]
Hi,
The WhoScored Parser is not working as expected because the dates have been changed to **Swahilli** from English and the dataframe is not able to process the dates.
![image](https://user-images.githubusercontent.com/65362417/221963903-731053f0-d31a-4ee3-9b7f-50c3f747bf71.png)
![image](https://user-images.githubusercontent.com/65362417/221964077-92dd7ae5-a45e-4c6a-9483-8faedd32f209.png)

**Comment by raaghule** [comment]
I found the reason for the error. It is related to the [fix]( https://github.com/probberechts/soccerdata/issues/126 ) . WhoScored uses Mac and Maa to denote March. The dictionary for Swahilli fix contains only Maa. I have fixed it in my local and it works like a charm. We need to map 'Mac' and 'Maa' to 'Mar'.

**Comment by probberechts** [comment]
Ok, thanks. Are you sure it also uses 'Maa' for March? To me it seems like it always use 'Mac' and that there is simply a typo in the current mapping.
