### ISSUE TITLE
Bugs and Error in OptaLoader's extract_lineups() function affecting "is_starter" & "minutes_played" columns (F7_XML)

### ISSUE THREAD

**Issue by npranav10** [ML-KULeuven/socceraction#48]
To make the bugs reproducible, I used the OptaLoader on the [XML feeds from test folder](https://github.com/ML-KULeuven/socceraction/tree/master/tests/data/opta) and have attached a screenshot here.

![bugs](https://user-images.githubusercontent.com/22992723/117415982-8c304300-af36-11eb-8dee-9571d1c88820.PNG)

I noticed  2 bugs which affect the columns **is_starter** and **minutes_played**. Both the bugs can be located in **extract_lineups()** function belonging to **_F7XMLParser** class. There is also an error possible in logic used to calculate **minutes_played** (refer Issue 3 on this page )

**Issue 1: a possible bug**
Location : [Line 841 in spadl/opta.py](https://github.com/ML-KULeuven/socceraction/blob/master/socceraction/spadl/opta.py#L841) 

In `is_starter=player_elm.attrib['Formation_Place'] != 0,`, the attribute **Formation_Place** turns out to be a character containing numbers from 0 to 11. So in this case, _is_starter_ becomes _True_ irrespective of the value of **Formation_Place** because of difference in data types.

**Issue 2: a possible bug**
Location :  [Line 827 in spadl/opta.py](https://github.com/ML-KULeuven/socceraction/blob/master/socceraction/spadl/opta.py#L827) 

The following piece of code 
` sub_on = int(next((item['Time'] for item in subst if item['SubOn'] == f'p{player_id}'), 0)) `

assigns value 0 to variable **sub_on** for substitutes who don't get subbed on. So the players who stay on the bench throughout the game have the value of **minutes_played** to be equal to **stats['match_time']**, because `minutes_played = sub_off - sub_on` and the sub_off value for all players who don't get subbed off is set to **stats['match_time']**. So as seen from the picture above, Iturraspe a player who doesn't play a single minute in the game, has minutes_played = 96 - 0 = 96

**Issue 3 : possible Error causing line:**
Location :  [Line 827 in spadl/opta.py](https://github.com/ML-KULeuven/socceraction/blob/master/socceraction/spadl/opta.py#L827) 
Substitutions events in Opta doesn't necessarily have to involve 2 players. A player retirement is also part of the sub event. So when a player gets retired (i.e. team has exhausted its available sub opportunities), the **Subtitution** element will not have the '**SubOn**' attribute but just the '**SubOff**'. Hence one would get a **KeyError** in these circumstances as the list comprehension looks for **SubOn** key in each **Subtitution** element

P.S  : I managed a fix locally for all the 3 issues and will be issuing a pull request momentarily. I thought posting this as an issue would create a log of this issue on the issues section of this repo and might help people in the future.

**Comment by npranav10** [comment]
The following table would help us undestand how the new logic for variable **sub_on** works

scenario | sub_on time | sub_off time
-- | -- | --
player starts game and ends game without getting subbed off/ retired | 0 | stats['match_time']
player starts game and gets subbed off/retired in event A | 0 | value of item['SubOff'] in event A
player gets subbed on in event A and ends game without getting subbed off/ retired | value of item['SubOn'] in event A | stats['match_time']
player gets subbed on in event A and subbed off/retired in event B | value of item['SubOn'] in event A | value of item['SubOff'] in event B

Screenshots

Before Fix
![before_fix](https://user-images.githubusercontent.com/22992723/117427701-ef27d700-af42-11eb-9260-8ca6fc1e5b34.PNG)


After Fix

![after_fix](https://user-images.githubusercontent.com/22992723/117427736-f818a880-af42-11eb-9157-e005ea5c7f7e.PNG)

And regarding the player retirement issue, I tested the code on a private F7 XML file and got the expected results. Happy to discuss more on the issues if there is a lack of clarity in my words.

**Comment by probberechts** [comment]
Thanks for the very detailed bug report and fixes. The `opta._F9JSONParser` was affected by the same issues. The most recent commit should have fixed the bug for both parsers.
