### ISSUE TITLE
ModuleNotFoundError: No module named 'socceraction.data'

### ISSUE THREAD

**Issue by twhelan22** [ML-KULeuven/socceraction#57]
I am getting this error when running 1-load-and-convert-statsbomb-data.ipynb using the latest version. Here is the code from the notebook:
`from socceraction.data.statsbomb import StatsBombLoader`
Which gives an error.

The following works, however:
`from socceraction.socceraction.data.statsbomb import StatsBombLoader`

This is an issue for all imports, e.g. StatsBombLoader requires:
`from socceraction.data.base import EventDataLoader, ParseError`

**Comment by probberechts** [comment]
Thanks for your bug report! The `socceraction.data` module was not included in the latest pip release. It should be fixed if you upgrade:
```sh
pip install socceraction==1.1.1
```

**Comment by twhelan22** [comment]
Yep works, thanks for the quick fix!
