### ISSUE TITLE
Atomic SPADL - Mini dribbles added

### ISSUE THREAD

**Issue by castrodiego** [ML-KULeuven/socceraction#657]
Hi, I'm currently using Statsbomb Open Data and while analysing atomic actions, I realised that mini dribbles are being added. For some reason, dribbles that have less than 3 meters of distance (the lower bound defined in the documentation) are being generated.

If you take this notebook (https://github.com/ML-KULeuven/socceraction/blob/master/public-notebooks/ATOMIC-1-load-and-convert-statsbomb-data.ipynb) and add these lines before the final plots, you'll be able to reproduce the issue:

```
min_dribble_length: float = 3.0
max_dribble_length: float = 60.0

atomic_dribbles = atomic_actions[atomic_actions.type_name=="dribble"]
atomic_dribbles["total_distance"]=np.sqrt(atomic_dribbles.dx**2+atomic_dribbles.dy**2)
atomic_dribbles["far_enough"] = atomic_dribbles.dx**2 + atomic_dribbles.dy**2 >= min_dribble_length**2
atomic_dribbles["not_too_far"] = atomic_dribbles.dx**2 + atomic_dribbles.dy**2 <= max_dribble_length**2

atomic_dribbles.far_enough.value_counts()
```
Some False values will appear in the result.

Socceraction version: 1.5.0

Regards,
Diego

**Comment by probberechts** [comment]
There are two kinds of dribbles in SPADL:
1. Dribbles defined in the raw event stream data. These have an `original_event_id`.
2. Synthetic dribbles, generated to fill gaps between two events

The constraint for the length of dribbles is only applied to the synthetic dribbles. 

This seems to work as expected:
```python
>>> assert atomic_dribbles[~atomic_dribbles.far_enough & atomic_dribbles.original_event_id.isnull() ].empty
True
```

**Comment by castrodiego** [comment]
You are right Pieter, the mini-dribbles  that I was seeing come directly from Statsbomb data. I got confused because SPADL documentation defines dribbles with a lenght constraint:
![image](https://github.com/ML-KULeuven/socceraction/assets/6389614/423e855a-13a9-43ad-baa2-118fffda19da)
(https://socceraction.readthedocs.io/en/latest/documentation/spadl/SPADL_definitions.html)

**Comment by probberechts** [comment]
Indeed, good catch. I'll update the docs.
