### ISSUE TITLE
SPADL: Gamestate features with null result

### ISSUE THREAD

**Issue by castrodiego** [ML-KULeuven/socceraction#662]
It seems that the method **result** from socceraction/vaep/features.py is generating null values.

![image](https://github.com/ML-KULeuven/socceraction/assets/6389614/165060c8-5531-417e-a410-6041f8c6631b)

I believe that changing **spadlcgf.actiontypes** to **spadlcfg.results** will fix it.

Regards,
Diego

**Comment by probberechts** [comment]
Thats indeed a copy-paste bug. Good  catch!
