### ISSUE TITLE
[Opta] Deflected non-goal shots should have result="fail"

### ISSUE THREAD

**Issue by Razccoo** [ML-KULeuven/socceraction#725]
Sorry if worded weirdly, didn't know how else to describe it.

I noticed that end_x mean values of succesful shots (goals) was not 105. When digging deeper, I found that during the conversion of 'attempt saved' events to shots, some get a success value for result.

I like to tinker with a customized package and change features or variables for my personal needs, and originally thought that it was my custom code that could have broken it, as the package installed through pip didn't have this issue. However, when I used a cleanly installed new local package I got the same issue again.

I am unable to figure out what is causing it.
[shots_local_package.csv](https://github.com/ML-KULeuven/socceraction/files/15402973/shots_local_package.csv)
[shots_pip_package.csv](https://github.com/ML-KULeuven/socceraction/files/15402974/shots_pip_package.csv)

**Comment by probberechts** [comment]
Which data provider?

**Comment by Razccoo** [comment]
Whoscored

**Comment by Razccoo** [comment]
[1761311.json](https://github.com/ML-KULeuven/socceraction/files/15404176/1761311.json)

I have attached the match json. Could you check if the bug is persistent on your side? It might be something that is caused by my setting, if you can't replicate it.

**Comment by Razccoo** [comment]
Found the issue! My pip installed socceraction package was still on version 1.5.0, so I managed to find the changed line of code that caused it.

Issue in opta.py

**_fix_unintentional_ball_touches** in Version 1.5.0
```python3
selector_deflected = (opta_type.shift(-1) == 'ball touch') & (opta_outcome.shift(-1) is True)
```

**_fix_unintentional_ball_touches** in Version 1.5.1
```python3
selector_deflected = (opta_type.shift(-1) == 'ball touch') & (opta_outcome.shift(-1))
```

**Comment by probberechts** [comment]
Thanks for debugging this already! Are you sure this is resolved in the latest version? If I'm not mistaken, the `... is True` was already removed in version 1.5.0

Actually, this seems to be an edge case. The `_fix_unintentional_ball_touches` method was added to deal with deflected passes. It sets the result of a deflected pass to "success" if the team manages to keep possession. But your example seems to be a shot that was deflected. The result of a shot should depend on whether a goal was scored, not on whether possession is kept. Do you have any idea what the Opta event sequence for successful deflected shots (i.e., goals) looks like?

**Comment by Razccoo** [comment]
It is actually the removal of `... is True` that is causing the bug, with it it works like it is supposed to.
