### ISSUE TITLE
Query Regarding goal_from_shot function

### ISSUE THREAD

**Issue by yureed** [ML-KULeuven/socceraction#745]
Trying to use the goal_from_shot function for my Euros data from whoscored
![image](https://github.com/ML-KULeuven/socceraction/assets/41127970/8acf161d-2a8b-4383-a37f-7dd7f9517bf9)

It messes up for a lot of the different matches. It marks some shots as a goal. For instance, for Georgia vs Czechia rn, it showed me Czechia scored 2 goals. Then for Scotland vs Switzerland, it also messed up. I can go on, but I assume you get the point.
I am not sure if this is an issue regarding the WhoScored data or if its this function messing up. 
Appreciate your help, Thank you.

**Comment by probberechts** [comment]
I think I might have just fixed this in #741.

**Comment by yureed** [comment]
Doesn't seem to work for me. I have added the latest files. Maybe I am doing something wrong? I have used this before multiple times. 
I used spadl to convert the actions and then at the end, i used goal_from_shot for vaep labels to finalize.

**Comment by yureed** [comment]
Update: Tried restarting multiple times after changing files. Didnt work then reinstalled, then it worked. Don't know what happened here. Thank you for your help. Sorry for any inconvenience caused.
