### ISSUE TITLE
soccerdata ahead of socceraction

### ISSUE THREAD

**Issue by lehoff** [ML-KULeuven/socceraction#797]
I was getting started with soccerdata as the first step on my football analytics journey and when I wanted to investigate SPADL output from soccerdata I had to add socceraction, but there is a dependency problem:

```
Because no versions of socceraction match >1.5.3,<2.0.0
 and socceraction (1.5.3) depends on lxml (>=4.9.3,<5.0.0), socceraction (>=1.5.3,<2.0.0) requires lxml (>=4.9.3,<5.0.0).
And because soccerdata (1.8.2) depends on lxml (>=5.0.0,<6.0.0), socceraction (>=1.5.3,<2.0.0) is incompatible with soccerdata (1.8.2).
So, because footballdata depends on both soccerdata (1.8.2) and socceraction (^1.5.3), version solving failed.
```

As there is an overlap in contributors between soccerdata and soccerdata I would like to hear if there is anything fundamental that stop bumping lxml on socceraction. If not, I could try to patch things up and submit a PR, but if there is anything deeper than a version mismatch I would draw a blank :-)

**Comment by probberechts** [comment]
Thanks for reporting this. It should have been fixed in https://github.com/probberechts/soccerdata/pull/692.

**Comment by michaelromagne** [comment]
Hi ! It happens again now : 
`soccerdata 1.8.2 requires lxml<6.0.0,>=5.0.0, but you have lxml 4.9.4 which is incompatible.`
