### ISSUE TITLE
adding pressure

### ISSUE THREAD

**Issue by madestro** [ML-KULeuven/socceraction#802]
Hello

There is any chance to add (as canon ;-) ) in SPADL a new column marking the opponent which is making pressure on the play (or -1 if nobody), I (as a coach) am very interested in to check the difference between pressed or not pressed pass / headers / shots for my players.  Also I think StatsBomb have a flag to mark them

Let me know if it is a good idea,

Regards!
Javier

**Comment by probberechts** [comment]
There are no plans to add pressing to SPADL since it is not supported by all providers. But if you are working with StatsBomb data and want to add pressure-related columns to the SPADL dataframe you can so easily by merging on the `original_event_id` column.
