### ISSUE TITLE
SPADL-Opta bug in `keeper_save` type event.

### ISSUE THREAD

**Issue by Alek050** [ML-KULeuven/socceraction#850]
Hi,

First of all, really a great package. Thanks for open sourcing this!

I found a small issue related to transforming opta data to SPADL format. As I understand from the [spadl definitions](https://socceraction.readthedocs.io/en/latest/documentation/spadl/SPADL_definitions.html), a `keeper_save` can on be performed by an actual goalkeeper. However, when transforming opta data from f24/f7 to SPADL representation, I get 6 different players that perform a `keeper_save` event. See the code below (I had to anonimse the ids for obvious reasons).

```python
from socceraction.data.opta import OptaLoader, parsers
import socceraction.spadl as spadl

opta_loader = OptaLoader(
  root=MY_ROOT,
  feeds = {
    "f7": "competition_{competition_id}/{season_id}/{game_id}_f7.xml",
    "f24": "competition_{competition_id}/{season_id}/{game_id}_f24.xml",
  },
  parser={
      "f7": parsers.F7XMLParser,
      "f24": parsers.F24XMLParser
  }
)

game = opta_loader.games(MY_COMPETITION_ID, MY_SEASON_ID).iloc[0]

spadl_actions = spadl.add_names(
    spadl.opta.convert_to_actions(
      opta_loader.events(game["game_id"]),
      home_team_id=game["home_team_id"]
    )
  )
player_ids_value_counts = spadl_actions.loc[spadl_actions["type_name"]=="keeper_save", "player_id"].value_counts()
player_ids_value_counts.index = [f"player_{i}" for i in range(len(player_ids_value_counts.index))]
print(player_ids_value_counts)
```
```bash
player_0    2
player_1    2
player_2    1
player_3    1
player_4    1
player_5    1
Name: count, dtype: int64
```
Just to be sure I checked the match, but indeed there were no 6 goalkeepers in this match.

I am guessing a `save` event by Opta is not necessarily performed by a goalkeeper, something which the Opta SPADL converter seems to rely on in `socceraction.spadl.opta.py` in the `_get_type_id` method:
```python
elif eventname == "save":
    a = "keeper_save"
```

**Comment by probberechts** [comment]
Indeed, a "save" event can _"also be an outfield player event with qualifierId 94 for blocked shot."_ We should check wether the player that executes the save event is a goalkeeper and, if not, label it as a `non_action`.
